# Automatically generated by Terraform (storage_node module).
# Do not edit manually; change modules/storage_node/ansible_templates/storage_inventory.tpl instead.
# This fragment is read together with any other files in ansible/inventory.d/.

[storage]
%{ for _, node in nodes ~}
${node.ip} ansible_user=${node.user}
%{ endfor ~}

# Self-contained connection vars so the storage nodes can be configured even
# when the cluster fragment (10-cluster.ini) is absent.
[storage:vars]
ansible_ssh_private_key_file=${ssh_private_key_path}
cluster_admin_user=${vm_user}
cluster_admin_home=/home/${vm_user}
