k3s_api_port: 6443

cilium_chart_version: "1.19.1"
cilium_values_url: "https://raw.githubusercontent.com/m0r4a/homelab/main/apps/infrastructure/cilium/values-pre-kps.yaml"

k3s_install_script_url: "https://get.k3s.io"
helm_install_script_url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
flux_install_script_url: "https://fluxcd.io/install.sh"

cilium_cli_stable_url: "https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt"
hubble_cli_stable_url: "https://raw.githubusercontent.com/cilium/hubble/main/stable.txt"

allow_reboot_on_update: true

ansible_python_interpreter: auto_silent
