# Automatically generated by Terraform (k3s_cluster module).
# Do not edit manually; change modules/k3s_cluster/ansible_templates/inventory.tpl instead.
# This fragment is read together with any other files in ansible/inventory.d/.

[control_plane]
%{ for _, node in nodes ~}
%{ if node.role == "control-plane" ~}
${node.ip} ansible_user=${node.user}
%{ endif ~}
%{ endfor ~}

[worker]
%{ for _, node in nodes ~}
%{ if node.role == "worker" ~}
${node.ip} ansible_user=${node.user}
%{ endif ~}
%{ endfor ~}

[k3s_cluster:children]
control_plane
worker

[all:vars]
ansible_ssh_private_key_file=${ssh_private_key_path}
k3s_control_plane_ip=${control_plane_ip}
k3s_cluster_cidr=${cluster_cidr}
k3s_service_cidr=${service_cidr}
cluster_admin_user=${vm_user}
cluster_admin_home=/home/${vm_user}
